### ISSUE TITLE
CP index

### ISSUE THREAD

**Issue by diptiSH** [mmhs013/pyHomogeneity#1]
CP value index starts from 0 or 1? e.g. if I get CP as 14 then would it be 14th data point or 15th?

**Comment by mmhs013** [comment]
@diptiSH , It is a 0 based index system. So CP 14 means change point at the 15th data point.
But, if your data is a Pandas DataFrame with DateTime index, then it returns exact point values, That's means, if CP is '1980-01-01', then change point at '1980-01-01'.

The main concept of this type of CP values that, you easily slice your data using cp values like `data[:cp]` or `data.loc[:cp]`. No matter what type of data is.
