### ISSUE TITLE
mathematics in propability p in __pettitt

### ISSUE THREAD

**Issue by PLSeuJ** [mmhs013/pyHomogeneity#2]
hey,

just want to check. in the code for the pettitt test  
[line 201](https://github.com/mmhs013/pyHomogeneity/blob/c2defa8065cabdc00f835d33de725a5f416d8faf/pyhomogeneity/pyhomogeneity.py#L201) the exponential function is multiplied with 2. hence the propability is ranging from 0 to 2 instead of 0 to 1...

Is this an issue or handled elsewhere, which i didn't see?

**Comment by mmhs013** [comment]
@PLSeuJ, Sorry for the late response.
This equation is directly collected from [Pettitt (1979)](https://doi.org/10.2307/2346729) original paper (Equation 2.12). I think this is OK.

**Comment by PLSeuJ** [comment]
sorry, I myself wasn't available now. I guess it's all right, if it is in the original paper. I will investigate further though, as it is different to a script I use (that one could be wrong too of cause).

**Comment by mmhs013** [comment]
@PLSeuJ , If you find something wrong, please let me know. I will correct it. Thanks for your interest in my package. :slightly_smiling_face:
